config/routes.rb
Rails.application.routes.draw do
  resources :companies, only: [:new, :edit, :update, :create]
  resources :positions do 
    resources :applicants, only: [:index]
  end
  resources :applicants, only: [:new, :create]
  root 'home#index'
  devise_for :users

  get "/vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/position.rb
class Position < ApplicationRecord
  # as positions ou vagas pertence a empresa
  belongs_to :company
  # enum é um array, que guarda a posição no array como numeros, começando por 0, 
  enum career: [:developer, :business_inteligence, :information_technology, :design, :product, :technology, :other]

  enum contract: [:clt, :pj, :match]
  # para mudar o texto 
  has_rich_text :description
  # validação para os campos 
  validates :name, :career, :contract, :city, :state, :sumary, presence: true
  # depois de salva chama a set_slug
  before_save :set_slug 
  # uma vaga pode ter varios candidatos
  has_many :applicants 

  private 
  # criar uma url da vaga
  def set_slug 
    self.slug = "#{self.company.name.parameterize}-#{self.name.parameterize}"
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_i18n_careers, :set_i18n_contracts, except: [:public_position]
  before_action :set_position, only: [:edit, :show, :update]
  
  def index
    @positions = @company.positions
  end

  def new
    @position = @company.positions.new
  end

  def edit
  end

  def show
  end

  def create 
    @position = @company.positions.new(params_position)
    if @position.save 
      flash[:success] = 'Vaga cadastrada com sucesso.'
      redirect_to positions_path
    else  
      render :new
    end
  end

  def update 
    if @position.update(params_position)
      redirect_to positions_path
    else  
      render :edit
    end
  end

  def public_position 
    @position = Position.find_by(slug: params[:slug ])
    if user_signed_in?
      @applicant = current_user.applicants.new(position_id: @position.id)
    end

    respond_to do |format|
      format.html 
      format.js { render partial: 'applicants/new' }
    end
  end  

  private 

  def set_position 
    @position = @company.positions.find(params[:id])
  end

  def params_position
    params.require(:position).permit(:name, :career, :contract, :remote, :publish, :city, :state, :sumary, :description)
  end

  def set_company 
    redirect_to new_company_path if current_user.company.nil?
    @company = current_user.company 
  end

  def set_i18n_careers
    @careers = I18n.t('activerecord.attributes.position.careers')
  end

  def set_i18n_contracts 
    @contracts = I18n.t('activerecord.attributes.position.contracts')
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
    # cria a mensagem de texto para o link
    def text_position(position)
        "A empresa #{position.company.name} em #{position.city} está com a vaga de #{position.name}. Veja mais detalhes no nosso mural! #{url_position(position)}"
    end
    # cria o link para position
    def url_position(position)
        public_position_url(position.slug)
    end

    def career_name(career)
        I18n.t('activerecord.attributes.position.careers')[career.to_sym]
    end

    def contract_name(contract)
        I18n.t('activerecord.attributes.position.contracts')[contract.to_sym]
    end

    def modality(position)
        position.remote ? 'Remote': 'Presencial'
    end
end

app/views/positions/_form.html.haml
= simple_form_for @position do |f|
  .mt-3
    = f.input :name
  .mt-3
    = f.input :career, as: :select, collection: @careers, label_method: :second, value_method: :first, include_blank: false, selected: @position.career
  .mt-3
    = f.input :contract, as: :select, collection: @contracts, label_method: :second, value_method: :first, include_blank: false, selected: @position.contract
  .mt-3
  = f.input :remote 
  = f.input :publish 
  .mt-3
    = f.input :city 
  .mt-3
    = f.input :state, as: :select, collection: Brazil.states, label_method: :second, value_method: :first
  .mt-3
    = f.input :sumary, maxlength: 360, input_html: { class: 'count-textarea', rows: 4 } 
  -# mostra o numero de caracteres no textarea
  #the-count  
    %span#current 0
    %span#maximun / 360
  .mt-3
    %label Descrição
    = f.rich_text_area :description 
  .mt-3
    = f.button :submit, class: "btn btn-primary"

app/views/positions/_position.html.haml
.card-position 
  .card-body 
    .container.container-card 
      .row 
        .col-2 
          = image_tag position.company.logo, alt: "Logo marca da empresa #{position.company.name}", class: 'card-img-top'
        .col-10 
          %h4= position.name
          %h5= "#{career_name(position.career)} - #{position.city} - #{contract_name(position.contract)}" 
          %p Lorem ipsum dolor sit, amet consectetur adipisicing elit. In voluptatibus perferendis a nulla repudiandae quas dolore obcaecati eum nihil sint! Corrupti ex perspiciatis atque, dolore corporis dicta ratione assumenda neque?
          .row
            .col-sm.mt-3 
              = link_to 'Ver mais', public_position_path(position.slug), class: 'btn btn-danger'
              - if user_signed_in? 
                - if !UserApplicantQuery.new(current_user.id, position.id).call
                  = link_to 'Candidatar-se', public_position_path(position.slug), {:remote => true, "data-bs-target" => "#modal", "data-bs-toggle" => "modal", class: 'btn btn-success'}
            .col-sm.mt-3.group-social-network.mx-10
              = render partial: 'shared/social_network', locals: {position: position}

app/views/positions/edit.html.haml
%h2 Editar vaga
= render "form"

app/views/positions/index.html.haml
%h2 Minhas vagas

%table.table 
  %thead.table-dark 
    %tr 
      %th{:scope => "col"} Título
      %th{:scope => "col"} Carreira
      %th{:scope => "col"} Local
      %th{:scope => "col"} Tipo de contrato
      %th{:scope => "col"} Candidaturas
      %th{:scope => "col"} Ações
  %tbody
    - @positions.each do |position| 
      %tr
        %th{:scope => "row"}= position.name 
        %td= career_name(position.career)
        %td= modality(position) # aplicar helper
        %td= contract_name(position.contract)
        %td
          - if position.applicants.size > 0
            = link_to "Ver aplicações (#{position.applicants.count})", position_applicants_path(position), class: 'btn btn-warning btn-sm'
        %td 
          = link_to 'Editar', edit_position_path(position), class: "btn btn-primary btn-sm"

app/views/positions/new.html.haml
%h2 Publica vaga
= render "form"

app/views/positions/public_position.html.haml
-# Pagiana de detalhes 
-# imprime o nome da vaga e da empresa
%h2= "#{@position.name} - #{@position.company.name}" 
-# mostra o nome da carreira, a cidade, estado e etc. 
%p= "#{career_name(@position.career)} - #{@position.city} / #{modality(@position)}, #{@position.state} - #{contract_name(@position.contract)}"
-# mostra a descrição da vaga 
= @position.description 
-# renderiza a parte social, os icones 
%br/
%h5 Compartilhar  
= render partial: 'shared/social_network', locals: {position: @position}

.wrapper-form-applicant.mt-3 
  - if user_signed_in? 
    - if !UserApplicantQuery.new(current_user.id, @position.id).call
      %p= "Você já aplicou para essa vaga."
    - else 
      %p= "Insira suas informações abaixo para se candidatar à vaga de #{@position.name}"
      = render 'applicants/form' 
  - else 
    %p Você precisa está logado para se candidatar
  

app/views/positions/show.html.haml
%h1 Positions#show
%p Find me in app/views/positions/show.html.haml